
package View;


import Model.VentanaControl;




public class FormMain extends javax.swing.JFrame {
    
   
    public String user;    
     
 
    
    VentanaControl obj_serviciog = new VentanaControl();   
    
 
       
    public FormMain() {
        
        initComponents();
  
        
        obj_serviciog.Init_window_frame("Gestion","/Imagenes/icono_zoo.jpg",  this);
        
        
   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        btnRegistrar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrar3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(616, 442));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setText("Registrar Orden");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 270, 40));

        btnRegistrar1.setText("Registrar Clientes");
        btnRegistrar1.setToolTipText("");
        btnRegistrar1.setMaximumSize(new java.awt.Dimension(74, 23));
        btnRegistrar1.setMinimumSize(new java.awt.Dimension(74, 23));
        btnRegistrar1.setPreferredSize(new java.awt.Dimension(74, 23));
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 270, 40));

        btnRegistrar2.setText("Registro Comidas a Menus");
        btnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 270, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("GESTION DE MATERIAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 440, 50));

        btnRegistrar3.setText("Registrar Menus");
        btnRegistrar3.setMaximumSize(new java.awt.Dimension(74, 23));
        btnRegistrar3.setMinimumSize(new java.awt.Dimension(74, 23));
        btnRegistrar3.setPreferredSize(new java.awt.Dimension(74, 23));
        btnRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, 40));

        jMenu2.setText("File");

        jMenuItem2.setText("Regirstro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //llama la ventana de dialogo
        
        GrupoUsuDialog objetoDialoag = new GrupoUsuDialog(this,true);
        System.out.println("usuario FOR MAIN" + user );   
        System.out.println("error en panel");  
        objetoDialoag.user = "laura"; 
                         
        objetoDialoag.setVisible(true);
        

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
        ClienteDialog objetoDialoag = new ClienteDialog(this,true);
        objetoDialoag.setVisible(true);
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar2ActionPerformed
        // TODO add your handling code here:
        ComidaDialog objetoDialoag = new ComidaDialog(this,true);
        objetoDialoag.setVisible(true);
    }//GEN-LAST:event_btnRegistrar2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar3ActionPerformed
        // TODO add your handling code here:
        MenuDialog objetoDialog = new MenuDialog(this,true);
        objetoDialog.show();
    }//GEN-LAST:event_btnRegistrar3ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JButton btnRegistrar2;
    private javax.swing.JButton btnRegistrar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
